import sys, os
from qtpy import QtWidgets

# Import graphics generated by QtPy program. 
from ui_data_conversion.mainwindow import Ui_MainWindow

# Use Pandas to import geographic waypoints for local frame (east-north-up) origins.
import pandas as pd

## Widen path to import from shared modules folder, which contains the extra 
# modules that are imported. First create path to modules.
module_dir = os.path.join( '..', 'shared_modules' )
# Append modules path. 
sys.path.append(module_dir)

ultra_module_dir = os.path.join( '..', '..', 'shared_modules' )
# Append modules path. 
sys.path.append(ultra_module_dir)

# Import the module with the coordinate transformation routines.
# E.g., from folder.filename import class as alias
from coordinate_transform_class import Transform as xfrm
# Functions will be instances of class,e.g., xfrm.llh2lle(...)

# Import extra functions for data processing and plotting.
from extras import sec2HMS, kml_rkt_header, kml_dot_array, kml_placemark

# Import rasterio function to get geoid heights from Earth Gravitational Model 
# (EGM) file.
import rasterio
from pathlib import Path
# Set path to EGM gtx file.
egm_path = Path(os.path.join("proj", "egm08_25.gtx"))
try:
    src = rasterio.open(egm_path)
    # Set EGM file flag to true, if found.
    xfrm.egm_file_flag = True
except: 
    print("egm08_25.gtx file not found in proj/")
    print("Can't perform geoid undulation calculations.")
    # Set EGM file flag to false, if missing.
    xfrm.egm_file_flag = False

# Instantiate app.
app = QtWidgets.QApplication(sys.argv)

# class for tidying up code.
# ~.QMainWindow -- inherits from QMainWindow.
class mainWindow(QtWidgets.QMainWindow):
    # Initialize GUI.
    def __init__(self, parent = None):
        super().__init__(parent)
        self.ui_data_conversion = Ui_MainWindow()
        self.ui_data_conversion.setupUi(self)

        # Set GUI window title.
        self.setWindowTitle("Data Converter")

        # Connect menu file selection with file_open routine.
        self.ui_data_conversion.actionFile.triggered.connect(self.file_open)

        # Share some variables used across routines.
        global filepath, trackpoint_size

        ''' Signal and slot connections '''
        # Connect GUI process button with onProcessClick routine.
        self.ui_data_conversion.btnProcess.clicked.connect(self.onProcessClick)

        # Connect the input and output file type selection radio buttons to the respective routines.
        self.ui_data_conversion.radBtnInputENU.clicked.connect(self.set_input_file_type_enu)
        self.ui_data_conversion.radBtnInputLLH.clicked.connect(self.set_input_file_type_llh)
        self.ui_data_conversion.radBtnInputLLE.clicked.connect(self.set_input_file_type_lle)
        self.ui_data_conversion.radBtnInputEFG.clicked.connect(self.set_input_file_type_efg)

        self.ui_data_conversion.radBtnOutputENU.clicked.connect(self.set_output_file_type_enu)
        self.ui_data_conversion.radBtnOutputLLH.clicked.connect(self.set_output_file_type_llh)
        self.ui_data_conversion.radBtnOutputLLE.clicked.connect(self.set_output_file_type_lle)
        self.ui_data_conversion.radBtnOutputEFG.clicked.connect(self.set_output_file_type_efg)
        self.ui_data_conversion.radBtnOutputKML.clicked.connect(self.set_output_file_type_kml)
        self.ui_data_conversion.radBtnOutputECI_to_ECEF.clicked.connect(self.set_output_file_type_ecef)
        
        # If geoid undulation file is not found, disable LLE radiobuttons. 
        if xfrm.egm_file_flag == True: 
            self.ui_data_conversion.radBtnInputLLE.setEnabled(True)
            self.ui_data_conversion.radBtnOutputLLE.setEnabled(True)
        else: 
            self.ui_data_conversion.radBtnInputLLE.setEnabled(False)
            self.ui_data_conversion.radBtnOutputLLE.setEnabled(False)

        # Simplify the input reference frame origin combo box object name.
        self.in_cb = self.ui_data_conversion.comboBoxInputRef
        # Connect input reference frame combo box with selectionchange routine.
        self.in_cb.currentIndexChanged.connect(self.in_selectionchange)

        # Simplify the output reference frame origin combo box object name.
        self.out_cb = self.ui_data_conversion.comboBoxOutputRef
        # Connect input reference frame combo box with selectionchange routine.
        self.out_cb.currentIndexChanged.connect(self.out_selectionchange)

        ''' Open the configuration file, dataconversion.cfg, to read the values 
        from the previous session. Check if the configuration file exists, if 
        not set filepath = "."
        '''
        try:
            cfg_file = []
            with open('dataconversion.cfg', "r") as fcfg:
                for line in fcfg:
                    # If any line is blank or if the first line is a comment 
                    # line beginning with "#."
                    if not line.strip() or line.strip()[0] == "#":
                        pass
                    else:
                        cfg_file.append(line.strip())
            # Set working directory that contains input and output files.
            self.ui_data_conversion.txtDirpath.setText(cfg_file[0])
            # Set selected input file.
            self.ui_data_conversion.txtFileIn.setText(cfg_file[1])
            # Initially set "filepath" to the directory path and input file name.
            # The input filepath can be changed by the user through the menu if desired.
            filepath = os.path.join(cfg_file[0], cfg_file[1])
            
            # Set the input file type radio buttons.
            if cfg_file[2] == 'True':
                self.ui_data_conversion.radBtnInputENU.setChecked(True)
                self.set_input_file_type_enu()
            if cfg_file[3] == 'True':
                self.ui_data_conversion.radBtnInputLLH.setChecked(True)
                self.set_input_file_type_llh()
            if cfg_file[4] == 'True':
                self.ui_data_conversion.radBtnInputLLE.setChecked(True)
                self.set_input_file_type_lle()
            if cfg_file[5] == 'True':
                self.ui_data_conversion.radBtnInputEFG.setChecked(True)
                self.set_input_file_type_efg()
    
            # Set the input local coordinate frame origin combo box selection value, e.g., "L-20."
            self.ui_data_conversion.comboBoxInputRef.setCurrentIndex(int(cfg_file[6]))
            # Set the input coordinate text box values: latitude, longitude, & HAE.
            self.ui_data_conversion.txtInputLatitude.setText(cfg_file[7])
            self.ui_data_conversion.txtInputLongitude.setText(cfg_file[8])
            self.ui_data_conversion.txtInputHAE.setText(cfg_file[9])
    
            # Set the output file type radio buttons.
            if cfg_file[10] == 'True':
                self.ui_data_conversion.radBtnOutputENU.setChecked(True)
                self.set_output_file_type_enu()
            if cfg_file[11] == 'True':
                self.ui_data_conversion.radBtnOutputLLH.setChecked(True)
                self.set_output_file_type_llh()
            if cfg_file[12] == 'True':
                self.ui_data_conversion.radBtnOutputLLE.setChecked(True)
                self.set_output_file_type_lle()
            if cfg_file[13] == 'True':
                self.ui_data_conversion.radBtnOutputEFG.setChecked(True)
                self.set_output_file_type_efg()
            if cfg_file[14] == 'True':
                self.ui_data_conversion.radBtnOutputKML.setChecked(True)
                self.set_output_file_type_kml()
            if cfg_file[15] == 'True':
                self.ui_data_conversion.radBtnOutputECI_to_ECEF.setChecked(True)
                self.set_output_file_type_ecef()
            # Set the KML dot size, e.g., "1.0"
            try: 
                self.ui_data_conversion.txtTrackpointSize.setText(cfg_file[16])
                trackpoint_size = cfg_file[16]
            except:
                trackpoint_size = "1.0"
    
            # Set the output local coordinate frame origin combo box selection value, e.g., "L-20."
            try: 
                self.ui_data_conversion.comboBoxOutputRef.setCurrentIndex(int(cfg_file[17]))
            except:
                pass

            # Write the output coordinate text box values: latitude, longitude, & HAE.
            # Allow that the text boxes can't be written to; they may be grayed out. 
            try:
                self.ui_data_conversion.txtOutputLatitude.setText(cfg_file[18])
            except: 
                pass
            try:
                self.ui_data_conversion.txtOutputLongitude.setText(cfg_file[19])
            except:
                pass
            try:
                self.ui_data_conversion.txtOutputHAE.setText(cfg_file[20])
            except:
                pass

            # Import the local coordinate frame origin waypoints for east-north-up
            # (ENU) coordinate frame transformations. 
            datafilepath = os.path.join(".", "data", "waypoints.csv")

            # Share the waypoint dataframe values for the selection change routines. 
            global wp_df
            
            wp_df = pd.read_csv(datafilepath)
            # Add waypoint list to both input and output reference frame origin 
            # combo boxes' menus.
            for waypoint in wp_df['Waypoint']:
                # Add menu item to each combo box.
                self.in_cb.addItem(waypoint)
                self.out_cb.addItem(waypoint)

        except:
            # Set the configuration file path to the current folder.
            filepath = "."
            print("Configuration file not found - new one is created.")

    '''Set the input file type, e.g., "LLH", "LLE," &c. When any input file type 
        but "ENU" is selected, the input local reference frame group box is grayed 
        out, as no local reference frame is required. Certain input file types 
        will gray-out some output file types; a KML output will not be computed 
        with an ENU nor an EFG input file type, only with either a LLH or a LLE 
        input file type.
        Note: by using the instance "xfrm" of the class Transform, the input_file_type
        variable is global. 
    '''
    def set_input_file_type_llh(self):
        # Set input_file_type as a member of class Transform, for it to be global.
        xfrm.input_file_type = "llh"
        # Disable output LLH selection; don't want to create same output datatype 
        # as input datatype. 
        self.ui_data_conversion.radBtnOutputLLH.setEnabled(False)
        
        # Enable these output selections.
        # If geoid undulation file is not found, disable LLE radiobutton. 
        if xfrm.egm_file_flag == True: 
            self.ui_data_conversion.radBtnOutputLLE.setEnabled(True)
        else: 
            self.ui_data_conversion.radBtnOutputLLE.setEnabled(False)
        self.ui_data_conversion.radBtnOutputEFG.setEnabled(True)
        self.ui_data_conversion.radBtnOutputKML.setEnabled(True)
        self.ui_data_conversion.txtTrackpointSize.setEnabled(True)
        self.ui_data_conversion.labelTrackpoint.setEnabled(True)
        self.ui_data_conversion.radBtnOutputECI_to_ECEF.setEnabled(True)

        # Disable input group box, containing the input local reference frame 
        # coordinates.
        self.ui_data_conversion.boxInputRefFrame.setEnabled(False)

    def set_input_file_type_lle(self):
        # Again, input_file_type is a class member of Transform; it is global.
        xfrm.input_file_type = "lle"
        # Disable output LLE selection; don't want to create same datatype.
        self.ui_data_conversion.radBtnOutputLLE.setEnabled(False)

        # Enable these output selections.
        self.ui_data_conversion.radBtnOutputLLH.setEnabled(True)
        self.ui_data_conversion.radBtnOutputEFG.setEnabled(True)
        self.ui_data_conversion.radBtnOutputKML.setEnabled(True)
        self.ui_data_conversion.txtTrackpointSize.setEnabled(True)
        self.ui_data_conversion.labelTrackpoint.setEnabled(True)
        self.ui_data_conversion.radBtnOutputECI_to_ECEF.setEnabled(True)

        # Disable input group box, containing the input local reference frame coordinates.
        self.ui_data_conversion.boxInputRefFrame.setEnabled(False)

    def set_input_file_type_efg(self):
        xfrm.input_file_type = "efg"
        # Disable output EFG selection; don't want to create same datatype.
        self.ui_data_conversion.radBtnOutputEFG.setEnabled(False)

        # Enable these output selections.
        self.ui_data_conversion.radBtnOutputLLH.setEnabled(True)
        # If geoid undulation file is not found, disable LLE radiobutton. 
        if xfrm.egm_file_flag == True: 
            self.ui_data_conversion.radBtnOutputLLE.setEnabled(True)
        else: 
            self.ui_data_conversion.radBtnOutputLLE.setEnabled(False)

        # Disable these output selections.
        self.ui_data_conversion.radBtnOutputKML.setEnabled(False)
        self.ui_data_conversion.txtTrackpointSize.setEnabled(False)
        self.ui_data_conversion.labelTrackpoint.setEnabled(False)
        self.ui_data_conversion.boxInputRefFrame.setEnabled(False)
        self.ui_data_conversion.radBtnOutputECI_to_ECEF.setEnabled(False)

    def set_input_file_type_enu(self):
        xfrm.input_file_type = "enu"
        # Enable these output selections.
        self.ui_data_conversion.radBtnOutputLLH.setEnabled(True)
        
        # If geoid undulation file is not found, disable LLE radiobutton. 
        if xfrm.egm_file_flag == True: 
            self.ui_data_conversion.radBtnOutputLLE.setEnabled(True)
        else: 
            self.ui_data_conversion.radBtnOutputLLE.setEnabled(False)

        self.ui_data_conversion.radBtnOutputEFG.setEnabled(True)

        # Disable these output selections.
        self.ui_data_conversion.radBtnOutputKML.setEnabled(False)
        self.ui_data_conversion.txtTrackpointSize.setEnabled(False)
        self.ui_data_conversion.labelTrackpoint.setEnabled(False)
        self.ui_data_conversion.radBtnOutputECI_to_ECEF.setEnabled(False)

        # Enable input group box, containing the input local reference frame coordinates.
        self.ui_data_conversion.boxInputRefFrame.setEnabled(True)

    '''Set the output file type. When any output file type but ENU is selected, 
        the output local reference frame group box is grayed out, as no local 
        reference frame is required.
    '''
    def set_output_file_type_llh(self):
        xfrm.output_file_type = "llh"
        # Disable output group box, containing the input local reference frame coordinates.
        self.ui_data_conversion.boxOutputRefFrame.setEnabled(False)

    def set_output_file_type_lle(self):
        xfrm.output_file_type = "lle"
        # Disable output group box, containing the input local reference frame coordinates.
        self.ui_data_conversion.boxOutputRefFrame.setEnabled(False)

    def set_output_file_type_efg(self):
        xfrm.output_file_type = "efg"
        # Disable output group box, containing the input local reference frame coordinates.
        self.ui_data_conversion.boxOutputRefFrame.setEnabled(False)

    def set_output_file_type_kml(self):
        xfrm.output_file_type = "kml"
        # Disable output group box, containing the input local reference frame coordinates.
        self.ui_data_conversion.boxOutputRefFrame.setEnabled(False)

    def set_output_file_type_ecef(self):
        xfrm.output_file_type = "ecef"
        # Disable output group box, containing the input local reference frame coordinates.
        self.ui_data_conversion.boxOutputRefFrame.setEnabled(False)

    def set_output_file_type_enu(self):
        xfrm.output_file_type = "enu"
        # Enable output group box, containing the input local reference frame coordinates.
        self.ui_data_conversion.boxOutputRefFrame.setEnabled(True)

    '''Routine to connect with input reference frame (ENU) origin combo box menu 
        selection. "i" is the menu item number. '''
    def in_selectionchange(self, i):
        # Share flgInput_ref_origin flag value with "enu" input_file_type routine.
        global flgInput_ref_origin

        # Simplify object name.
        self.cb = self.ui_data_conversion.comboBoxInputRef

        # "waypoint" is name of geographic waypoint, e.g., "L-20."
        waypoint = self.cb.currentText()
        # Get latitude, longitude, and HAE of waypoint. If waypoint is "User input" then
        #  get values during "onProcessClick" from text boxes that user entered.
        if i > 0:
            # Set the output reference origin flag to false, indicating that the 
            # user-input local reference frame text boxes are not to be read for 
            # a special local origin for e-n-u data.
            flgInput_ref_origin = False

            # Get the latitude, longitude, and HAE from the selected data frame line.
            xfrm.input_ref_origin = wp_df.loc[wp_df['Waypoint'] == waypoint].values.tolist()[0][1:4]
            lat = xfrm.input_ref_origin[0]
            lon = xfrm.input_ref_origin[1]
            hae = xfrm.input_ref_origin[2]

            # Set GUI text box values. Latitude and longitude are set to 6 decimal
            # places, while the height or elevation is to 3. 
            self.ui_data_conversion.txtInputLatitude.setText("{:.6f}".format(lat))
            self.ui_data_conversion.txtInputLongitude.setText("{:.6f}".format(lon))
            self.ui_data_conversion.txtInputHAE.setText("{:.3f}".format(hae))
        else:
            # Set the input reference origin flag to true, indicating that the 
            # user-input local reference frame text boxes are to be read for a 
            # special local origin for e-n-u data.
            flgInput_ref_origin = True

    '''Routine to connect with output reference frame (ENU) origin combo box menu 
        selection. "i" is the menu item number. '''
    def out_selectionchange(self, i):
        # Share flgOutput_ref_origin flag value with "enu" output_file_type routine.
        global flgOutput_ref_origin

        # Simplify object name.
        self.cb = self.ui_data_conversion.comboBoxOutputRef

        # "waypoint" is name of geographic waypoint, e.g., "L-20."
        waypoint = self.cb.currentText()
        # Get latitude, longitude, and HAE of waypoint. If waypoint is "User input" then
        #  get values during "onProcessClick" from text boxes that user entered.
        if i > 0:
            # Set the output reference origin flag to false, indicating that the 
            # user-input local reference frame text boxes are not to be read for 
            # a special local origin for e-n-u data.
            flgOutput_ref_origin = False

            # Get the latitude, longitude, and HAE from the selected data frame line.
            xfrm.output_ref_origin = wp_df.loc[wp_df['Waypoint'] == waypoint].values.tolist()[0][1:4]
            lat = xfrm.output_ref_origin[0]
            lon = xfrm.output_ref_origin[1]
            hae = xfrm.output_ref_origin[2]

            # Set GUI text box values.
            #self.ui_data_conversion.txtOutputLatitude.setText(str(latitude))
            self.ui_data_conversion.txtOutputLatitude.setText("{:.6f}".format(lat))
            self.ui_data_conversion.txtOutputLongitude.setText("{:.6f}".format(lon))
            self.ui_data_conversion.txtOutputHAE.setText("{:.3f}".format(hae))
        else:
            # Set the output reference origin flag to true, indicating that the user-input local
            # reference frame text boxes are to be read for a special local origin for e-n-u data.
            flgOutput_ref_origin = True

    '''With menu selection get file path.'''
    def file_open(self):
        # Share filepath with other routines. 
        global filepath

        # Get the name of the menu selected file. Start the browser from the last 
        # session, at "filepath."
        name = QtWidgets.QFileDialog.getOpenFileName(self, 'Open File', filepath)
        filepath = name[0]

        # Split the input file path into the working directory and input file for 
        # the file text boxes.
        dirpath, filein = os.path.split(filepath)

        # Set txtDirpath text box with working directory.
        self.ui_data_conversion.txtDirpath.setText(dirpath)
        # Set txtFileIn text box with input file.
        self.ui_data_conversion.txtFileIn.setText(filein)

    '''Process data.'''
    def onProcessClick(self):
        # Create output file name: append base file name with "-" then add input 
        # extension and a "." and then the file output extension, e.g., 
        # data.llh becomes data-llh.lle

        # The path and file name separated before the last dot.
        filepath_prefix, file_extension = filepath.rsplit('.', 1)

        # Combine the file-name pieces. Allow for special names for a ECI to ECEF 
        # conversion.
        if xfrm.output_file_type == "ecef":
            fileoutpath = "{}-eci.{}".format(filepath_prefix, file_extension)
        else:             
            fileoutpath = "{}-{}.{}".format(filepath_prefix, file_extension, xfrm.output_file_type)

        # Set txtFileOut text box with output file.
        fileout = os.path.split(fileoutpath)[1]
        self.ui_data_conversion.txtFileOut.setText(fileout)

        # Clear the input file header text box for the next processed file.
        self.ui_data_conversion.txtHeader.setText("")

        # Save the text box values and user selections to the configuration file, 
        # dataconversion.cfg, for the next time the program starts. this is done 
        # before starting the processing, in case the processing doesn't work.
        with open('dataconversion.cfg', "w") as fcfg:
            # Write a header line describing the configuration file. .
            fcfg.write("# This file contains the data converter's screen values from the last session.\n")

            # Write working directory that contains input and output files.
            fcfg.write(self.ui_data_conversion.txtDirpath.text() + '\n')
            # Write selected input file.
            fcfg.write(self.ui_data_conversion.txtFileIn.text() + '\n')

            # Write the input file type selection state: "ENU"
            fcfg.write(str(self.ui_data_conversion.radBtnInputENU.isChecked()) + '\n')
            # Write the input file type selection state: "LLH"
            fcfg.write(str(self.ui_data_conversion.radBtnInputLLH.isChecked()) + '\n')
            # Write the input file type selection state: "LLE"
            fcfg.write(str(self.ui_data_conversion.radBtnInputLLE.isChecked()) + '\n')
            # Write the input file type selection state: "EFG"
            fcfg.write(str(self.ui_data_conversion.radBtnInputEFG.isChecked()) + '\n')

            # Write the input local coordinate frame origin combo box selection value, e.g., "L-20."
            fcfg.write(str(self.ui_data_conversion.comboBoxInputRef.currentIndex()) + '\n')
            # Write the input coordinate text box values: latitude, longitude, & HAE.
            fcfg.write(str(self.ui_data_conversion.txtInputLatitude.text()) + '\n')
            fcfg.write(str(self.ui_data_conversion.txtInputLongitude.text()) + '\n')
            fcfg.write(str(self.ui_data_conversion.txtInputHAE.text()) + '\n')

            # Write the output file type selection state: "ENU"
            fcfg.write(str(self.ui_data_conversion.radBtnOutputENU.isChecked()) + '\n')
            # Write the output file type selection state: "LLH"
            fcfg.write(str(self.ui_data_conversion.radBtnOutputLLH.isChecked()) + '\n')
            # Write the output file type selection state: "LLE"
            fcfg.write(str(self.ui_data_conversion.radBtnOutputLLE.isChecked()) + '\n')
            # Write the output file type selection state: "EFG"
            fcfg.write(str(self.ui_data_conversion.radBtnOutputEFG.isChecked()) + '\n')
            # Write the output file type selection state: "KML"
            fcfg.write(str(self.ui_data_conversion.radBtnOutputKML.isChecked()) + '\n')
            # Write the output file type selection state: "ECI_to_ECEF"
            fcfg.write(str(self.ui_data_conversion.radBtnOutputECI_to_ECEF.isChecked()) + '\n')
            # Write the KML dot size, e.g., "1.0"
            fcfg.write(str(self.ui_data_conversion.txtTrackpointSize.text()) + '\n')

            # Write the output local coordinate frame origin combo box selection value, e.g., "L-20."
            fcfg.write(str(self.ui_data_conversion.comboBoxOutputRef.currentIndex()) + '\n')
            # Write the output coordinate text box values: latitude, longitude, & HAE.
            fcfg.write(str(self.ui_data_conversion.txtOutputLatitude.text()) + '\n')
            fcfg.write(str(self.ui_data_conversion.txtOutputLongitude.text()) + '\n')
            fcfg.write(str(self.ui_data_conversion.txtOutputHAE.text()) + '\n')

            # Write an ending.
            fcfg.write("# End of file.")

        # If input file type is E-N-U, with a local coordinate frame origin, get 
        # the coordinates, either from the input combo box, or from the user 
        # entered text box values.
        if xfrm.input_file_type == "enu":
            if flgInput_ref_origin:
                refin_lat_deg = float(self.ui_data_conversion.txtInputLatitude.text())
                refin_lon_deg = float(self.ui_data_conversion.txtInputLongitude.text())
                refin_hae = float(self.ui_data_conversion.txtInputHAE.text())
            else:  # Use the comboBoxInputRef value for a local reference frame origin.
                refin_lat_deg = xfrm.input_ref_origin[0]
                refin_lon_deg = xfrm.input_ref_origin[1]
                refin_hae = xfrm.input_ref_origin[2]
                (refE, refF, refG) = xfrm.llh2efg(self, refin_lat_deg, refin_lon_deg, refin_hae)

        # If output file type is E-N-U, with a local coordinate frame origin, get 
        # the coordinates, either from the output combo box, or from the user 
        # entered text box values.
        if xfrm.output_file_type == "enu":
            if flgOutput_ref_origin:
                refout_lat_deg = float(self.ui_data_conversion.txtOutputLatitude.text())
                refout_lon_deg = float(self.ui_data_conversion.txtOutputLongitude.text())
                refout_hae = float(self.ui_data_conversion.txtOutputHAE.text())
            else:  # Use the comboBoxOutputRef value for a local reference frame origin.
                refout_lat_deg = xfrm.output_ref_origin[0]
                refout_lon_deg = xfrm.output_ref_origin[1]
                refout_hae = xfrm.output_ref_origin[2]
                (refE, refF, refG) = xfrm.llh2efg(self, refout_lat_deg, refout_lon_deg, refout_hae)

        '''If output file type is "KML," convert ECEF geodetic (LLH) or orthometric 
            (LLE) latitude, longitude, & height coordinates to Keyhole markup 
            language (KML) track points, that can be uploaded to Google Earth.

            <!-- Example of a KML file header: -->
            <?xml version="1.0" encoding="UTF-8"?>
            <kml xmlns="http://earth.google.com/kml/2.1">
            <Document>

            <!-- Example of a track KML file segment for a single track point: --> 
            <Placemark>
                <name></name>
                <description></description>
                <Point>
                    <coordinates>
                        35.86911316, -117.71322875, 836.398
                    </coordinates>
                </Point>
            </Placemark>

            <!-- Example of a KML file ending: -->
            </Document>
            </kml>
        '''
        # Open the input and output files. 
        with open(filepath, "r") as fin:
            with open(fileoutpath, "w", encoding="utf-8") as fout:
                # Write the header line. 
                if xfrm.output_file_type == "llh" or xfrm.output_file_type == "ecef":
                    # Both will be latitude-longitude-HAE output types.
                    fout.write("     time  latitude(deg) longitude(deg)   HAE(m)\n")
                elif xfrm.output_file_type == "lle":
                    fout.write("     time  latitude(deg) longitude(deg) elevation(m)\n")
                elif xfrm.output_file_type == "efg":
                    fout.write("     time        E              F              G (ECEF in meters)\n")
                elif xfrm.output_file_type == "kml":
                    # If the output file is a staged rocket KML trackpoint file,
                    # print the KML header to the output file.
                    header_txt = kml_rkt_header(fileout)
                    fout.write(header_txt)
                elif xfrm.output_file_type == "enu":
                    fout.write("     time(sec)   east            north        up (in meters)\n")
                    
                # Get the time from the first data line. Set first data line flag 
                # to true.
                flgFirst = True
                for line in fin:
                    # If line is emply continue to next line.
                    if line.strip() == "":
                        continue

                    # Record the start time of data. The first number of the line 
                    # should be a timestamp; usually a float.
                    strTime = line.split()[0]
                    # Get only the integer value of the first time, so that the 
                    # "isnumeric()" test works.
                    strIntTime = strTime.split('.')[0]
                    # If input file has non-data header, e.g., "Time  x  y  z," write 
                    # the line to the header text box, then continue in the loop.
                    if not strIntTime.isnumeric():
                        self.ui_data_conversion.txtHeader.setText(line)
                    else: # If numeric data.
                        # For the first line of data, record the start time of data, 
                        # and some other initialization.
                        if flgFirst:
                            # If the input file type is LLH or LLE, find the number
                            # of rocket stages on the first line, if any. 
                            if xfrm.input_file_type == "llh" or xfrm.input_file_type == "lle":
                                # If file has number of stages at end of first line, 
                                # otherwise make only 1 stage. 
                                try: 
                                    num_stages = int(line.split()[-1])
                                except:
                                    num_stages = 1
    
                                # Output the KML dot types. This makes the KML 
                                # output symbol  a colored dot, and allows for 
                                # several different colors if the data file has
                                # more than one rocket stages. Also, the dot size 
                                # (trackpoint_size) is forwarded to the routine. 
                                if xfrm.output_file_type == "kml":
                                    # Get the KML array of dot styles. 
                                    dot_list = kml_dot_array(num_stages, trackpoint_size)
                                    # Write the icon list to the KML file.
                                    for i in range(num_stages):
                                        fout.write(dot_list[i])
                                
                            # Round off to milli-seconds.
                            start_time = float(strTime)
                            self.ui_data_conversion.txtStartTimeSec.setText("{:.3f}".format(start_time))
                            # Convert the seconds to hr:min:sec, to allow seconds 
                            # to be expressed as hours, minutes,and seconds. 
                            str_start_HMS = sec2HMS(start_time)
                            self.ui_data_conversion.txtStartTimeHMS.setText(str_start_HMS)
                            
                            # Indicate that the first line is processed, and skip 
                            # this operation next time thru loop. 
                            flgFirst = False
                        
                        # Extract the x-y-z position data, e.g., east-north-up, 
                        # latitude-longitude-HAE, &c. Note, latitude is 'x,' and 
                        # longitude is 'y.'
                        time = float(strTime)
                        x = float(line.split()[1])
                        y = float(line.split()[2])
                        z = float(line.split()[3])
                        #print("{}, {}, {}, {}".format(time, x, y, z))
                        
                        # Extract the 5th column stage number, if present. If not, 
                        # set stage index to 1. 
                        # A fifth column stage number will allow a rocket 
                        # trajectory to have a different color for each stage.
                        try:
                            stage_index = int(line.split()[4]) - 1
                        except:
                            stage_index = 1
    
                        # Process output file type Keyhole markup language (KML) 
                        # with special handling. Input will only be either a LLH 
                        # or a LLE input file.
                        if xfrm.output_file_type == "kml":
                            # Placemark format. 
                            '''
                            str_HMS = sec2HMS(time)
                            fout.write('   <Placemark>\n')
                            fout.write('      <name> </name>\n')
                            fout.write('      <description>' + strTime + ' (' + str_HMS + ')</description>\n')
                            fout.write('      <styleUrl>#sh_shaded_dot_' + '0' + '</styleUrl>\n')
                            fout.write('      <Point>\n')
                            fout.write('         <extrude>1</extrude>\n')
                            fout.write('         <altitudeMode>absolute</altitudeMode>\n')
                            fout.write('         <coordinates>\n')
                            fout.write('            %.6f,%.6f,%.3f\n' % (y, x, z))
                            fout.write('         </coordinates>\n')
                            fout.write('      </Point>\n')
                            fout.write('   </Placemark>\n')
                            '''
                            # y, x, z: longitude, latitude, & HAE
                            placemark_txt = kml_placemark(time, x, y, z, stage_index)
                            fout.write(placemark_txt)

                        # Process input file types, then output file types.
                        # If input file is Earth-centered-inertial (ECI),
                        # and output file is Earth-centered-Earth-fixed (ECEF), 
                        # select LLH/LLE ECI to ECEF to fix to Earth's rotation.
                        # Must include the time from the start, i.e., delta_time = 
                        # t - start_time.
                        if xfrm.input_file_type == "llh":
                            if xfrm.output_file_type == "lle":
                                # Compute height over geoid, i.e. above mean sea level.
                                # Must also transfer "src" function for rasterio to work.
                                #orthometric_height = z - undulation
                                X, Y, Z = xfrm.llh2lle(self, src, x, y, z)
                                # Write data to file: longitude, latitude, & orthometric height.
                                fout.write("{0:10.3f}  {1:10.6f}  {2:13.6f}  {3:10.3f}\n".format(time, X, Y, Z))
                            elif xfrm.output_file_type == "efg":
                                # Call transform function.
                                X, Y, Z = xfrm.llh2efg(self, x, y, z)
                                # Write data to file.
                                fout.write("{0:10.3f}  {1:10.3f}  {2:13.3f}  {3:13.3f}\n".format(time, X, Y, Z))
                            elif xfrm.output_file_type == "ecef":
                                # Call transform function.
                                X, Y, Z = xfrm.llh2ecef(self, time - start_time, x, y, z)
                                # Write data to file.
                                fout.write("{0:10.3f}  {1:10.6f}  {2:13.6f}  {3:10.3f}\n".format(time, X, Y, Z))
                            elif xfrm.output_file_type == "enu":
                                # Call transform function.
                                X, Y, Z = xfrm.llh2enu(self, x, y, z, 
                                                       refout_lat_deg, refout_lon_deg, refout_hae)
                                # Write data to file.
                                fout.write("{0:10.3f}  {1:10.3f}  {2:13.3f}  {3:13.3f}\n".format(time, X, Y, Z))
                            
                        elif xfrm.input_file_type == "lle":
                            if xfrm.output_file_type == "llh":
                                # Compute height above ellipsoid (HAE).
                                # Must also transfer "src" function for rasterio to work.
                                #hae = orthometric_height + undulation
                                X, Y, Z = xfrm.lle2llh(self, src, x, y, z)
                                # Write data to file: longitude, latitude, & orthometric height.
                                fout.write("{0:10.3f}  {1:10.6f}  {2:13.6f}  {3:10.3f}\n".format(time, X, Y, Z))
                            elif xfrm.output_file_type == "efg":
                                # Convert to HAE first, then compute undulation 
                                # from EGM file using rasterio.
                                # Must also transfer "src" function for rasterio to work.
                                # Call transform function.
                                X, Y, Z = xfrm.lle2efg(self, src, x, y, z)
                                # Write data to file.
                                fout.write("{0:10.3f}  {1:10.3f}  {2:13.3f}  {3:13.3f}\n".format(time, X, Y, Z))
                            elif xfrm.output_file_type == "ecef":
                                # Must also transfer "src" function for rasterio to work.
                                # Call transform function.
                                X, Y, Z = xfrm.lle2ecef(self, src, time - start_time, x, y, z)
                                # Write data to file.
                                fout.write("{0:10.3f}  {1:10.6f}  {2:13.6f}  {3:10.3f}\n".format(time, X, Y, Z))
                            elif xfrm.output_file_type == "enu":
                                # Convert to HAE first, then compute undulation 
                                # from EGM file using rasterio.
                                # Must also transfer "src" function for rasterio to work.
                                # Call transform function.
                                X, Y, Z = xfrm.lle2enu(self, src, x, y, z, 
                                                       refout_lat_deg, refout_lon_deg, refout_hae)
                                # Write data to file.
                                fout.write("{0:10.3f}  {1:10.3f}  {2:13.3f}  {3:13.3f}\n".format(time, X, Y, Z))

                        elif xfrm.input_file_type == "efg":
                            if xfrm.output_file_type == "llh":
                                # Call transform function.
                                X, Y, Z = xfrm.efg2llh(self, x, y, z)
                                # Write data to file.
                                fout.write("{0:10.3f}  {1:10.3f}  {2:13.3f}  {3:10.3f}\n".format(time, X, Y, Z))
                            elif xfrm.output_file_type == "lle":
                                # Must also transfer "src" function for rasterio to work.
                                # Call transform function.
                                X, Y, Z = xfrm.efg2lle(self, src, x, y, z)
                                # Write data to file.
                                fout.write("{0:10.3f}  {1:10.6f}  {2:13.6f}  {3:10.3f}\n".format(time, X, Y, Z))
                            elif xfrm.output_file_type == "enu":
                                # Call transform function.
                                X, Y, Z = xfrm.efg2enu(self, x, y, z, 
                                                       refout_lat_deg, refout_lon_deg, refout_hae)
                                # Write data to file.
                                fout.write("{0:10.3f}  {1:12.3f}  {2:15.3f}  {3:15.3f}\n".format(time, X, Y, Z))

                        elif xfrm.input_file_type == "enu":
                            if xfrm.output_file_type == "llh":
                                # Call transform function.
                                X, Y, Z = xfrm.enu2llh(self, x, y, z, 
                                                       refin_lat_deg, refin_lon_deg, refin_hae)
                                # Write data to file.
                                fout.write("{0:10.3f}  {1:10.6f}  {2:13.6f}  {3:10.3f}\n".format(time, X, Y, Z))
                            elif xfrm.output_file_type == "lle":
                                # Must also transfer "src" function for rasterio to work.
                                # Call transform function.
                                X, Y, Z = xfrm.enu2lle(self, src, x, y, z, 
                                                       refin_lat_deg, refin_lon_deg, refin_hae)
                                # Write data to file.
                                fout.write("{0:10.3f}  {1:10.6f}  {2:13.6f}  {3:10.3f}\n".format(time, X, Y, Z))
                            elif xfrm.output_file_type == "efg":
                                # Call transform function.
                                X, Y, Z = xfrm.enu2efg(self, x, y, z, 
                                                       refin_lat_deg, refin_lon_deg, refin_hae)
                                # Write data to file.
                                fout.write("{0:10.3f}  {1:10.3f}  {2:13.3f}  {3:13.3f}\n".format(time, X, Y, Z))
                            elif xfrm.output_file_type == "enu":
                                # Call transform function.
                                X, Y, Z = xfrm.enu2enu(self, x, y, z, 
                                                       refin_lat_deg, refin_lon_deg, refin_hae, 
                                                       refout_lat_deg, refout_lon_deg, refout_hae)
                                # Write data to file.
                                fout.write("{0:10.3f}  {1:11.3f}  {2:14.3f}  {3:14.3f}\n".format(time, X, Y, Z))

                # After all data lines are written to the output file and if the output 
                # file is a Keyhole markup language (KML) track-point file for 
                # Google Earth processing, add the KML ending to the output file.
                if xfrm.output_file_type == "kml":
                    fout.write('</Document>\n')
                    fout.write('</kml>')

                #Write to the File Times panel start and stop times, and difference.
                self.ui_data_conversion.txtStartTimeSec.setText(str(start_time))
                # Record the stop time of data, and the length of time. Round off 
                # to milli-seconds.
                stop_time = round(time, 3)
                self.ui_data_conversion.txtStopTimeSec.setText(str(stop_time))
            
                # Convert the seconds to hr:min:sec.
                str_start_HMS = sec2HMS(start_time)
                self.ui_data_conversion.txtStartTimeHMS.setText(str_start_HMS)
                str_stop_HMS = sec2HMS(stop_time)
                self.ui_data_conversion.txtStopTimeHMS.setText(str_stop_HMS)
            
                # Calculate the length of the data.
                len_time = stop_time - start_time
                self.ui_data_conversion.txtLenTimeSec.setText("{:.3f}".format(len_time))
            
                # Convert the seconds to hr:min:sec.
                str_len_HMS = sec2HMS(len_time)
                self.ui_data_conversion.txtLenTimeHMS.setText(str_len_HMS)

        print("Wrote to file")

# Instantiate mainWindow class.
window = mainWindow()
# Show window.
window.show()
# Keeps window open.
sys.exit(app.exec_())
